version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      assignees:
        - "kajyr"
  - package-ecosystem: "npm"
    directory: "/pta-format"
    schedule:
      interval: "weekly"
      assignees:
        - "kajyr"
  - package-ecosystem: "npm"
    directory: "/pta-tools"
    schedule:
      interval: "weekly"
      assignees:
        - "kajyr"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
     assignees:
      - 'kajyr'
    open-pull-requests-limit: 3